<a href="https://colab.research.google.com/github/USBondre/Edunet-Ms-Internship-Artificial-Intelligence/blob/main/Car_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#Step1: Importing Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
#Step2: Importing Dtataset
df = pd.read_csv('toyota.csv')
X = df.iloc[:,[0,1,3,4,5,6,7,8]].values
Y = df.iloc[:,[2]].values

In [9]:
print(X)

[[' GT86' 2016 'Manual' ... 265 36.2 2.0]
 [' GT86' 2017 'Manual' ... 145 36.2 2.0]
 [' GT86' 2015 'Manual' ... 265 36.2 2.0]
 ...
 [' Urban Cruiser' 2012 'Manual' ... 125 57.6 1.4]
 [' Urban Cruiser' 2011 'Manual' ... 125 50.4 1.3]
 [' Urban Cruiser' 2011 'Manual' ... 125 50.4 1.3]]


In [11]:
print(Y)


[[16000]
 [15995]
 [13998]
 ...
 [ 4995]
 [ 3995]
 [ 4495]]


In [12]:
#Step3: Data Preprocessing & Label Encoding
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,-4] = le2.fit_transform(X[:,-4])


In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[2])],remainder='passthrough')
X = ct.fit_transform(X)

In [14]:
print(X)


[[0.0 1.0 0.0 ... 265 36.2 2.0]
 [0.0 1.0 0.0 ... 145 36.2 2.0]
 [0.0 1.0 0.0 ... 265 36.2 2.0]
 ...
 [0.0 1.0 0.0 ... 125 57.6 1.4]
 [0.0 1.0 0.0 ... 125 50.4 1.3]
 [0.0 1.0 0.0 ... 125 50.4 1.3]]


In [15]:
#Step4: Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [16]:
print(X)

[[-0.80688656  0.87241516 -0.01218335 ...  2.30527356 -1.6950626
   1.2122702 ]
 [-0.80688656  0.87241516 -0.01218335 ...  0.68091453 -1.6950626
   1.2122702 ]
 [-0.80688656  0.87241516 -0.01218335 ...  2.30527356 -1.6950626
   1.2122702 ]
 ...
 [-0.80688656  0.87241516 -0.01218335 ...  0.41018802 -0.34367157
  -0.16347816]
 [-0.80688656  0.87241516 -0.01218335 ...  0.41018802 -0.79834519
  -0.39276955]
 [-0.80688656  0.87241516 -0.01218335 ...  0.41018802 -0.79834519
  -0.39276955]]


In [17]:
#Step5: Splitting Dataset into Training set and Test set
from sklearn.model_selection import train_test_split
(X_train,X_test,Y_train,Y_test) = train_test_split(X,Y,test_size=0.2,random_state=0)


In [18]:
#step6: Training Model
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(random_state=0)
regression.fit(X_train,Y_train)


/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(random_state=0)

In [20]:
y_pred = regression.predict(X_test)

In [21]:
#Step7: Testing result
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[11572.2  11295.  ]
 [18323.65 18995.  ]
 [ 9143.3   8950.  ]
 ...
 [ 9278.02  9233.  ]
 [24243.02 22498.  ]
 [12576.39 12295.  ]]


#Calculating Accuracy


In [22]:
from sklearn.metrics import r2_score,mean_absolute_error
r2_score(Y_test, y_pred)

0.965269422063879

In [23]:
mean_absolute_error(Y_test,y_pred)

805.9842928059206

In [24]:

print(y_pred)

[11572.2  18323.65  9143.3  ...  9278.02 24243.02 12576.39]


Reshape to 2D


In [25]:
print(Y_test)

[[11295]
 [18995]
 [ 8950]
 ...
 [ 9233]
 [22498]
 [12295]]


In [26]:
y_pred = np.reshape(y_pred,(-1,1))

Making Pandas DataFrame

In [27]:
mydata = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(mydata,columns=['Real Price','Predicted Price'])

In [28]:
print(dataframe)


      Real Price  Predicted Price
0        11295.0       11572.2000
1        18995.0       18323.6500
2         8950.0        9143.3000
3         9995.0        8384.1900
4        15990.0       19238.7000
...          ...              ...
1343     13998.0       15306.4665
1344     10495.0       10478.1500
1345      9233.0        9278.0200
1346     22498.0       24243.0200
1347     12295.0       12576.3900

[1348 rows x 2 columns]
